export const storeProducts = [
    {
        id: 1,
        title: "Needle & Thread Petunia Gown",
        img: "img/product-1.jpg",
        price: 2000,
        color: "CHAMPAGNE",
        size: "made to order",
        info: "This delicate gown features a ruffled bodice with intricate embroidery and a breezy, Swiss-dot tulle skirt. A soft ribbon detail, floral appliques, and scattered sequins make this look quintessentially romantic.",
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 2,
        title: "Wtoo by Watters Miles Gown",
        img: "img/product-2.jpg",
        price: 2700,
        color: "IVORY",
        size: "made to order",
        info: "Stretch mesh construction makes this airily layered, off-the-shoulder gown surprisingly effortless to wear, with shirred sleeves and a full skirt for romantic movement. A peek of eyelash lace adds elegant detail to the bodice. ",
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 3,
        title: "Sachin & Babi Branwell Gown",
        img: "img/product-3.jpg",
        price: 3400,
        color: "WHITE",
        size: "made to order",
        info: "Bold and incredibly chic in design, this column gown features a plunging neckline with a banded waist. A striking bow detail gathered at the back with a slight train guarantees a head-turning look. ",
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 4,
        title: "Sinclair Dress",
        img: "img/product-4.jpg",
        price: 1900,
        color: "NATURAL WHITE",
        size: "made to order",
        info: "The stretchy lining gives a subtle blush hue to the lightweight ivory tulle of this dress, while intricate beading across the bodice and down the illusion sleeves gives a glam accent to the effortless silhouette.",
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 5,
        title: "Wtoo by Watters Viola Gown",
        img: "img/product-5.jpg",
        price: 4500,
        color: "TAWNY",
        size: "made to order",
        info: "Bold, allover embroidery lends an undeniably regal air to this body-hugging gown. Covered buttons accent the translucent back, and the lining ends so that the long train is stunningly sheer. ",
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 6,
        title: "Needle & Thread Petunia Gown",
        img: "img/product-6.jpg",
        price: 3600,
        color: "STARK WHITE",
        size: "made to order",
        info: "Crafted of the softest, lightest tulle, this convertible dress features a stunning low back. Designed to be worn tied in the front or back, its sweetheart bodice and waist-defining ruching make it universally flattering.",
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: 7,
        title: "Odalis Gown",
        img: "img/product-7.jpg",
        price: 900,
        color: "ALABASTER",
        size: "made to order",
        info: "Made from intricate graphic lace, this fitted gown features a plunging v-neckline and dramatic train. The cascading flutter sleeves transform into a gorgeous cape detail to frame the open back. ",
        inCart: false,
        count: 0,
        total: 0
        },
    {
        id: 8,
        title: "Watters Brides Frederique Gown",
        img: "img/product-8.jpg",
        price: 7100,
        color: "PEARL",
        size: "made to order",
        info: "Leone lace is layered over this ballgown’s constructed corset bodice, complete with a high neckline and three-quarter sleeves. A soft netting skirt creates a grand silhouette, while a row of dainty bows at the back makes a charming finishing touch.",
        inCart: false,
        count: 0,
        total: 0
        },
    {
        id: 9,
        title: "Caron Dress",
        img: "img/product-9.jpg",
        price: 1800,
        color: "WHITE WINE",
        size: "made to order",
        info: "With spaghetti straps and a deep-v neckline, this versatile crepe midi dress is perfect for your upcoming event. Its feminine tulip skirt is gathered at the waist for a flattering finish.",
        inCart: false,
        count: 0,
        total: 0
        },
    {
        id: 10,
        title: "Odalis Gown",
        img: "img/product-10.jpg",
        price: 2100,
        color: "IVORY",
        size: "made to order",
        info: "Oversized floral appliques accent this gown's fitted bodice and float down the frothy A-line skirt, which extends into a slight train. A deep v-neckline, open back, and side cutouts reveal a bit of skin while two straps accentuate the waist.",
        inCart: false,
        count: 0,
        total: 0
        },
    {
        id: 11,
        title: "Amy Kuschel Redding Gown",
        img: "img/product-11.jpg",
        price: 1000,
        color: "STARK WHITE",
        size: "made to order",
        info: "Thoughtful details, like lace at the back and covered buttons on each wrist, elevate this structured crepe gown with a tailored silhouette and long sleeves.",
        inCart: false,
        count: 0,
        total: 0
        },
    {
        id: 12,
        title: "Nassau Gown",
        img: "img/product-12.jpg",
        price: 1400,
        color: "CHAMPAGNE",
        size: "made to order",
        info: "Long sleeves with subtle volume, a plunging neckline, and a sexy slit strike the perfect balance between bohemian romance and sultry edge. Scattered floral appliques add a feminine finish to this easygoing gown.",
        inCart: false,
        count: 0,
        total: 0
        },
];
  
  export const detailProduct = {
        id: 1,
        title: "Needle & Thread Petunia Gown",
        img: "img/product-1.jpg",
        price: 2000,
        color: "CHAMPAGNE",
        size: "made to order",
        info: "This delicate gown features a ruffled bodice with intricate embroidery and a breezy, Swiss-dot tulle skirt. A soft ribbon detail, floral appliques, and scattered sequins make this look quintessentially romantic.",
        inCart: false,
        count: 0,
        total: 0
  };